version: '3.8'
name: bookstore-java-project
services:
  db:
    image: postgres
    restart: no
    environment:
      - POSTGRES_DB=bookstore
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=bookstore
    volumes:
      - pgdata:/var/lib/postgresql/dat
    ports:
      - '22111:5432'
volumes:
  pgdata:
